name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 * * *"   # 原有的定时触发
  workflow_dispatch:      # 👈 新增这一行，允许手动点击运行

permissions:
  actions: write

jobs:
  keepalive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
