name: 葫芦侠三楼自动签到

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点（北京时间8点）执行
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # ✅ 使用可用的Python版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 执行签到
        env:
          HULUXIA_ACCOUNTS: ${{ secrets.HULUXIA_ACCOUNTS }}
        run: |
          python huluxia_signin.py
